// <auto-generated />
// Golden Test Fixtures for Classroom Visits V2
// Source: C:\Users\abdelrhman\Desktop\index.html
// SHA-256: 86302A58348798B5BAD6A250708B26677BC6E11ACE3CDEC5C272B2AC2FC47827
#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace AlFalah.Tests.Fixtures.ClassroomVisitsV2;

public static class ClassroomVisitsV2GoldenFixtures
{
    public const string PrototypeSha256 = "86302A58348798B5BAD6A250708B26677BC6E11ACE3CDEC5C272B2AC2FC47827";

    // ─── Classification Thresholds & Scale ───
    public const int TotalStandardsCount = 25;
    public const int TotalIndicatorsCount = 66;
    public const int TotalDomainsCount = 5;
    public const int MaxScorePerStandard = 4;
    public const int MinScorePerStandard = 1;
    public const int MaxTotalScore = 100;
    public const int DefaultInitialScorePerStandard = 1;
    public const int DefaultInitialTotalScore = 25;

    public const int ThresholdVeryHigh = 85;
    public const int ThresholdHigh = 65;
    public const int ThresholdMedium = 50;

    public const int ThresholdStrength = 75;
    public const int ThresholdWeakness = 65;

    public const string LevelVeryHighText = "متحقق بدرجة مرتفعة جداً";
    public const string LevelHighText = "متحقق بدرجة مرتفعة";
    public const string LevelMediumText = "متحقق بدرجة متوسطة";
    public const string LevelLowText = "متحقق بدرجة منخفضة";

    public static readonly ReadOnlyCollection<string> CsvHeaders = new(new[]
    {
        "رقم الزيارة",
        "تاريخ الزيارة",
        "رقم الحصة",
        "المعلم المزار",
        "رقم الهوية",
        "المادة الدراسية",
        "الصف والفصل",
        "عنوان الدرس",
        "نوع الزيارة",
        "عدد الحضور",
        "عدد الغياب",
        "المشرف الزائر",
        "صفة المشرف",
        "الدرجة الكلية (من 100)",
        "مستوى التحقق",
        "درجة بيئة التعلم (%)",
        "درجة التدريس والتعلم (%)",
        "درجة تنمية المهارات (%)",
        "درجة التقويم (%)",
        "درجة سلوك المتعلمين (%)",
        "نقاط القوة",
        "مجالات التحسين"
    });

    // ─── Evaluators Fixture ───
    public static readonly ReadOnlyCollection<GoldenEvaluatorFixture> Evaluators = new(new GoldenEvaluatorFixture[]
    {
        new(1, "ناصر بن جروض الزهراني", "مدير المدرسة"),
        new(2, "محيسن الحساني", "وكيل شؤون التعليم"),
        new(3, "عبد الإله الشريف", "وكيل شؤون الطلاب")
    });

    // ─── Treatment Plan Templates ───
    public static readonly IReadOnlyDictionary<string, GoldenTreatmentTemplateFixture> TreatmentTemplates =
        new Dictionary<string, GoldenTreatmentTemplateFixture>
        {
            [@"بيئة التعلم"] = new GoldenTreatmentTemplateFixture(
                @"بيئة التعلم",
                @"تحسين جودة بيئة التعلم وتنظيمها لتكون محفزة وآمنة لجميع المتعلمين",
                @"1. مراجعة توزيع المقاعد بما يضمن عدالة الرؤية والمشاركة.
2. إثراء الصف بمصادر تعلم مساندة ووسائل حسية متنوعة.
3. ضبط إدارة زمن الحصة بين مراحل الدرس (تمهيد، تدريس، تطبيق، غلق).",
                @"ارتفاع متوسط درجات بيئة التعلم إلى 80% أو أعلى في الزيارة القادمة."
            ),
            [@"التدريس والتعلم"] = new GoldenTreatmentTemplateFixture(
                @"التدريس والتعلم",
                @"تطوير استراتيجيات التدريس الحديثة وتنويعها لتلبية الفروق الفردية واستثمار التقنية",
                @"1. دمج استراتيجيات التعلم النشط (فكر-زاوج-شارك، التعلم التعاوني).
2. توظيف المنصات والتطبيقات الرقمية التفاعلية المرتبطة بهدف الحصة.
3. تقديم أمثلة ومهمات أدائية واقعية ترتبط بحياة الطلاب اليومية.",
                @"تطبيق استراتيجيتين حديثتين مع توظيف التقنية وتوثيق تفاعل المتعلمين بنسبة تتجاوز 85%."
            ),
            [@"تنمية المهارات"] = new GoldenTreatmentTemplateFixture(
                @"تنمية المهارات",
                @"الارتقاء بمهارات التفكير العليا والمهارات اللغوية والعددية والشخصية للطلاب",
                @"1. تضمين أسئلة تفكير ناقد وتفكير إبداعي مفتوحة النهاية (لماذا؟ كيف؟).
2. تفعيل أنشطة القراءة السريعة والكتابة الإجرائية أثناء المهام الصفية.
3. تشجيع العمل الجماعي وتبادل الأدوار لتعزيز الثقة والتواصل الإيجابي.",
                @"مبادرة الطلاب في طرح التساؤلات والتحليل بنسبة ملحوظة ورضا المشرف بنسبة 80% فأكثر."
            ),
            [@"التقويم"] = new GoldenTreatmentTemplateFixture(
                @"التقويم",
                @"تفعيل أساليب التقويم المستمر والمتنوع وتقديم التغذية الراجعة الفورية",
                @"1. تطبيق تقويم تشخيصي وتكويني خلال خطوات الحصة للتأكد من فهم كل مهارة.
2. استخدام أدوات تقويم سريعة (بطاقات الخروج، استبانات إلكترونية، أسئلة شفهية مدرجة).
3. تقديم تغذية راجعة تفسيرية توضح للطالب سبب الخطأ وكيفية معالجته.",
                @"حصر وتشخيص مستويات جميع الطلاب وتقديم دعم فوري للمتعثرين وتوثيق ذلك كتابياً."
            ),
            [@"سلوك المتعلمين"] = new GoldenTreatmentTemplateFixture(
                @"سلوك المتعلمين",
                @"تعزيز الانضباط الإيجابي وغرس الهوية الوطنية والمسؤولية الذاتية لدى المتعلمين",
                @"1. وضع وتذكير ميثاق وقواعد السلوك الصفي بالتراضي الإيجابي.
2. تحفيز التحدث باللغة العربية السليمة وربط مضامين الدرس بالاعتزاز بالوطن.
3. تمكين الطلاب من إدارة جزء من النشاط الذاتي لترسيخ الاعتماد على النفس.",
                @"انضباط تام واختفاء الملاحظات السلوكية ومبادرة ذاتية من الطلاب في تنفيذ المهام."
            ),
        };

    // ─── Domains, Standards, and Indicators Fixtures ───
    public static readonly ReadOnlyCollection<GoldenDomainFixture> Domains = new(new GoldenDomainFixture[]
    {
        new GoldenDomainFixture(
            1,
            @"بيئة التعلم",
            new GoldenStandardFixture[]
            {
                new GoldenStandardFixture(
                    1,
                    1,
                    @"تُنفّذ المدرسة برامج وأنشطة؛ لتعزيز القيم الإسلامية والهوية الوطنية لدى المتعلمين.",
                    new string[]
                    {
                        @"توظيف أمثلة أو أنشطة مرتبطة بالقيم الإسلامية",
                        @"ربط المحتوى بالهوية الوطنية وتضمين أنشطة تعزز الانتماء للوطن",
                    }
                ),
                new GoldenStandardFixture(
                    2,
                    2,
                    @"تنفذ المدرسة إجراءات تضمن مناخا آمنا للتعلم والنمو نفسيا واجتماعيا.",
                    new string[]
                    {
                        @"التعامل باحترام مع جميع المتعلمين",
                        @"شعور المتعلمين بالأمان داخل الصف والتعبير عن آرائهم دون خوف من الخطأ",
                        @"خلو البيئة من التنمر أو التهديد",
                    }
                ),
                new GoldenStandardFixture(
                    3,
                    3,
                    @"يتوافر في بيئة التعلم مصادر وأنشطة متنوعة للتعلم تلبي احتياجات المتعلمين، ومنهم ذوو الإعاقة والموهوبون.",
                    new string[]
                    {
                        @"تنوع الأنشطة وفق مستويات المتعلمين",
                        @"مراعاة الفروق الفردية (الإعاقة والموهوبين).",
                    }
                ),
                new GoldenStandardFixture(
                    4,
                    4,
                    @"يُدار الوقت في بيئة التعلم بفاعلية؛ لدعم التعلم وتلبية احتياجات المتعلمين، ومنهم ذوو الإعاقة والموهوبون.",
                    new string[]
                    {
                        @"الالتزام بتوقيت كل مرحلة من الدرس ( مقدمة - عرض - تطبيق – غلق )",
                        @"منح المتعلمين الذي يحتاجون وقتاً إضافياً فرصة إضافية دون الإخلال بجدول الحصة",
                        @"الانتقال السلس بين الأنشطة",
                    }
                ),
                new GoldenStandardFixture(
                    5,
                    5,
                    @"يُتاح للمتعلمين فرص متكافئة في الأنشطة والمناقشة الصفية، واستخدام مصادر التعلم.",
                    new string[]
                    {
                        @"إشراك جميع المتعلمين",
                        @"تنوع أساليب المشاركة",
                        @"عدالة توزيع الفرص وتشجيع الطلاب المنعزلين عن المشاركة",
                    }
                ),
            }
        ),
        new GoldenDomainFixture(
            2,
            @"التدريس والتعلم",
            new GoldenStandardFixture[]
            {
                new GoldenStandardFixture(
                    6,
                    6,
                    @"توفر المدرسة مصادر تعلم متنوعة تدعم تنفيذ المناهج؛ لتحقيق نواتج التعلم المستهدفة.",
                    new string[]
                    {
                        @"استخدام مصادر تعلم متنوعة داخل الحصة (عرض، فيديو، أوراق عمل، منصة رقمية).",
                        @"توظيف المصادر بشكل مباشر لخدمة هدف الدرس وليس للعرض فقط",
                        @"يظهر أثر استخدام المصادر على فهم المتعلمين ومشاركتهم أثناء الحصة",
                    }
                ),
                new GoldenStandardFixture(
                    7,
                    7,
                    @"ينفذ المعلم أنشطة واستراتيجيات تدريس تستوفي نواتج التعلم المستهدفة في المنهج، وتتسق معها بوضوح.",
                    new string[]
                    {
                        @"تنوع الأنشطة والاستراتيجيات المرتبطة بأهداف الدرس.",
                        @"وضوح ارتباط الأنشطة بنواتج التعلم.",
                        @"تحقق نواتج التعلم من خلال تنفيذ الأنشطة.",
                    }
                ),
                new GoldenStandardFixture(
                    8,
                    8,
                    @"تتنوع استراتيجيات التدريس وفقا لقدرات المتعلمين، وتراعي الفروق الفردية بينهم.",
                    new string[]
                    {
                        @"تنوع الاستراتيجيات وفق مستويات المتعلمين",
                        @"مراعاة الفروق الفردية أثناء التنفيذ",
                        @"مشاركة جميع المتعلمين حسب قدراتهم",
                    }
                ),
                new GoldenStandardFixture(
                    9,
                    9,
                    @"يستخدم المعلم مصادر تعلم رقمية تلبي احتياجات المتعلمين بمختلف فئاتهم.",
                    new string[]
                    {
                        @"استخدام مصادر رقمية متنوعة (منصة، فيديو، تطبيق) تخدم أهداف الدرس.",
                        @"تكييف استخدام المصادر الرقمية لتناسب مستويات واحتياجات جميع المتعلمين.",
                    }
                ),
                new GoldenStandardFixture(
                    10,
                    10,
                    @"تنفذ المدرسة أنشطة تعليم وتعلم تركز على تطبيقات عملية ترتبط بحياة المتعلمين:",
                    new string[]
                    {
                        @"تنفيذ أنشطة عملية يطبق فيها الطلاب ما تعلموه في مواقف من حياتهم اليومية.",
                        @"ربط المهارات والدرس بتجارب واقعية (مثل أمثلة من البيت أو المجتمع) لزيادة الفهم.",
                    }
                ),
            }
        ),
        new GoldenDomainFixture(
            3,
            @"تنمية المهارات",
            new GoldenStandardFixture[]
            {
                new GoldenStandardFixture(
                    11,
                    11,
                    @"تشجع بيئة التعلم داخل الصف على تنمية مهارات القراءة والكتابة لدى المتعلمين.",
                    new string[]
                    {
                        @"تضمين أنشطة قراءة وكتابة مرتبطة بالدرس",
                        @"تشجيع المتعلمين على التعبير والكتابة والمشاركة",
                        @"تصحيح الأخطاء والسلامة اللغوية",
                    }
                ),
                new GoldenStandardFixture(
                    12,
                    12,
                    @"تشجع بيئة التعلم داخل الصف على تنمية المهارات العددية (الحساب) لدى المتعلمين.",
                    new string[]
                    {
                        @"دمج أرقام، إحصائيات، أو تواريخ ضمن سياق الدرس لتعزيز الفهم",
                        @"تشجيع المتعلمين على استخدام مهارات التقدير (مثل: تقدير زمن المهمة، تقدير المسافات)",
                        @"استخدام المتعلمين للمصطلحات العددية (أكثر، أقل، ضعف، نسبة مئوية، الترتيب التسلسلي)",
                    }
                ),
                new GoldenStandardFixture(
                    13,
                    13,
                    @"تشجع الممارسات التدريسية على تنمية مهارات التفكير والبحث والابتكار لدى المتعلمين.",
                    new string[]
                    {
                        @"طرح أسئلة تفكير عليا (تحليل – تفسير – استنتاج) لماذا؟ كيف؟",
                        @"توجيه المتعلمين لاستخراج المعلومات من (الكتاب، مصادر خارجية، أو تجربة ذهنية)",
                        @"التشجيع على تقديم حلول غير معتادة أو اقتراح ""نهاية مختلفة"" أو ""تصميم فكرة""",
                    }
                ),
                new GoldenStandardFixture(
                    14,
                    14,
                    @"تشجع بيئة التعلم تنمية المهارات العاطفية والاجتماعية لدى المتعلمين.",
                    new string[]
                    {
                        @"تعزيز التعاون والعمل الجماعي بين الطلاب وبمهام محددة",
                        @"تنمية مهارات التواصل واحترام آراء الآخرين",
                        @"دعم الثقة بالنفس والتعبير عن المشاعر بشكل إيجابي",
                    }
                ),
                new GoldenStandardFixture(
                    15,
                    15,
                    @"يستخدم المعلم أساليب تحفيز تعزز الدافعية لدى المتعلمين.",
                    new string[]
                    {
                        @"يستخدم المعلم التعزيز الإيجابي (لفظي أو معنوي) لتحفيز جميع الطلاب",
                        @"يوظف أساليب تشجيعية متنوعة (نقاط – مسابقات – مكافآت - أوسمة)",
                        @"النجاح في جعل المتعلمين يبادرون بالمشاركة والحماس للأنشطة طوال وقت الحصة",
                    }
                ),
                new GoldenStandardFixture(
                    16,
                    16,
                    @"يشارك المتعلمون في أنشطة التعلم بفاعلية، ويستمتعون بها.",
                    new string[]
                    {
                        @"مبادرة المتعلمين للمشاركة وطرح الأسئلة بوضوح وحماس طوال الحصة",
                        @"انخراط المتعلمين في تنفيذ الأنشطة الصفية بتركيز عالٍ، مع الالتزام التام بالعمل الجماعي",
                        @"ظهور علامات البهجة والارتياح أثناء التعلم، مع الرغبة المستمرة في إكمال التحديات",
                    }
                ),
            }
        ),
        new GoldenDomainFixture(
            4,
            @"التقويم",
            new GoldenStandardFixture[]
            {
                new GoldenStandardFixture(
                    17,
                    17,
                    @"يستخدم المعلمون أساليب وأدوات تقويم متنوعة تشخيصية وبنائية وختامية؛ للكشف عن الفروق الفردية في مستويات أداء المتعلمين المختلفة.",
                    new string[]
                    {
                        @"استخدام التقويم في كافة مراحل الحصة (قبلي، بنائي أثناء الشرح، وختامي)",
                        @"توظيف أدوات متنوعة (مثل: الأسئلة الشفهية، الاختبارات القصيرة أو تطبيقات التقويم التقني).",
                        @"تصميم أسئلة ومهام تتناسب مع مستويات الطلاب المختلفة (المحتاجين للدعم، المتوسطين، والمتميزين)",
                    }
                ),
                new GoldenStandardFixture(
                    18,
                    18,
                    @"يطبق المعلم أساليب وأدوات تقويم متنوعة؛ لقياس مستوى تحقق نواتج التعلم المستهدفة في المنهج لدى المتعلمين.",
                    new string[]
                    {
                        @"يستخدم طرقاً مختلفة للقياس (مثل: الاختبارات القصيرة، الأنشطة الشفهية، أو المهام الأدائية).",
                        @"يتأكد أن كل سؤال أو نشاط يقيس فعلياً هدفاً محدداً من أهداف الدرس (نواتج التعلم)",
                        @"يستطيع من خلال التقويم تحديد مستوى كل طالب (من أتقن المهارة ومن يحتاج إلى دعم إضافي)",
                    }
                ),
                new GoldenStandardFixture(
                    19,
                    19,
                    @"يقدم المعلم تغذية راجعة متنوعة للمتعلمين حسب الموقف التعليمي تركز على تحسين أدائهم.",
                    new string[]
                    {
                        @"تقديم التعليق أو التصحيح للمتعلم أثناء أو فور انتهاء المهمة مباشرة لضمان الاستفادة.",
                        @"عدم الاكتفاء بقول (صح أو خطأ)، بل يوضح للمتعلم ""لماذا"" أخطأ وكيف يصحح مساره للوصول للحل الصحيح.",
                        @"استخدام طرقاً مختلفة للتغذية الراجعة (مثل: التصحيح الذاتي، تبادل التصحيح بين الزملاء، أو التوجيه الفردي).",
                    }
                ),
            }
        ),
        new GoldenDomainFixture(
            5,
            @"سلوك المتعلمين",
            new GoldenStandardFixture[]
            {
                new GoldenStandardFixture(
                    20,
                    20,
                    @"يظهر المتعلمون الاعتزاز بالقيم والهوية الوطنية.",
                    new string[]
                    {
                        @"التزام المتعلمين بالتحدث بلغة عربية سليمة طوال زمن الحصة",
                        @"اعتزاز المتعلمين بتاريخ ومنجزات الوطن ورموزه في مشاركاتهم وأثناء الأنشطة",
                        @"التمسك بالقيم والأخلاق الإسلامية في التعامل والسمت العام",
                    }
                ),
                new GoldenStandardFixture(
                    21,
                    21,
                    @"يظهر المتعلمون الاتجاهات الإيجابية نحو ذواتهم والآخرين.",
                    new string[]
                    {
                        @"إظهار الثقة بالنفس أثناء المشاركة وطرح الآراء.",
                        @"يحترم المتعلمون آراء زملائهم ويتعاملون بإيجابية ويشجعون بعضهم أثناء الأنشطة",
                    }
                ),
                new GoldenStandardFixture(
                    22,
                    22,
                    @"يظهر المتعلمون التزاما بالممارسات الصحية السليمة.",
                    new string[]
                    {
                        @"المحافظة على نظافة المكان والأدوات، والحرص على بيئة صفية صحية (تهوية وإضاءة).",
                        @"الالتزام بوضعية الجلوس الصحيحة، والاهتمام بالنظافة الشخصية والترتيب العام.",
                    }
                ),
                new GoldenStandardFixture(
                    23,
                    23,
                    @"يلتزم المتعلمون بقواعد السلوك والانضباط.",
                    new string[]
                    {
                        @"الالتزام بالتعليمات والنظام داخل الحصة دون تكرار التنبيه، والمحافظة على الهدوء",
                        @"الحرص على آداب الاستئذان قبل المشاركة، والالتزام بمواعيد بدء ونهاية الحصة.",
                    }
                ),
                new GoldenStandardFixture(
                    24,
                    24,
                    @"يظهر المتعلمون الاستقلالية، والقدرة على التعلم الذاتي.",
                    new string[]
                    {
                        @"الاعتماد على النفس في إنجاز المهام، والبحث عن المعلومة قبل طلب المساعدة.",
                        @"القدرة على التقييم الذاتي وتصحيح الأخطاء بناءً على التغذية الراجعة.",
                    }
                ),
                new GoldenStandardFixture(
                    25,
                    25,
                    @"يظهر المتعلمون الاعتزاز بثقافتهم واحترام التنوع الثقافي في المجتمع.",
                    new string[]
                    {
                        @"التعبير عن الاعتزاز بالثقافة والهوية الوطنية، وإظهار التقدير لثقافات ولهجات الآخرين.",
                        @"تجنب أي تعليقات سلبية تجاه الاختلافات الثقافية، والتعامل بروح الانفتاح والاحترام.",
                    }
                ),
            }
        ),
    });

    // ─── 5 Prototype Seeded Visits ───
    public static readonly ReadOnlyCollection<GoldenVisitFixture> SeededVisits = new(new GoldenVisitFixture[]
    {
        new GoldenVisitFixture(
            Id: 1726300000000L,
            Date: @"2026-09-14",
            Period: @"الحصة الثالثة",
            TeacherId: 18,
            TeacherName: @"عبدالله سليم",
            TeacherEmpId: @"10000018",
            Subject: @"رياضيات",
            Grade: @"الأول المتوسط",
            LessonTitle: @"المتغيرات والعبارات الجبرية",
            VisitType: @"أولى",
            Attendance: 25,
            Absence: 0,
            EvaluatorName: @"ناصر بن جروض الزهراني",
            EvaluatorRole: @"مدير المدرسة",
            TotalScore: 66,
            OverallLevel: @"متحقق بدرجة مرتفعة",
            Notes: @"1. زيادة التركيز على تنويع استراتيجيات التدريس بما يرفع مستوى مشاركة الطلاب ويجعلهم محورًا فاعلًا في عملية التعلم.
2. تعزيز الربط بين محتوى الدرس وحياة المتعلمين وواقعهم من خلال أمثلة وتطبيقات عملية قريبة من خبراتهم.
3. التوسع في طرح الأسئلة التي تنمي مهارات التفكير العليا، بحيث تتجاوز التذكر المباشر إلى التحليل والتفسير والاستنتاج وحل المشكلات.
4. تنويع أساليب التقويم أثناء الحصة للتحقق المستمر من تحقق نواتج التعلم لدى جميع الطلاب، والاستفادة من النتائج في تعديل التدريس.
5. تقديم تغذية راجعة نوعية وفورية للطلاب توضّح مواطن القوة وما يحتاج إلى تحسين، بدل الاكتفاء بالحكم على الإجابة بالصواب أو الخطأ.
6. مراعاة الفروق الفردية بين الطلاب من خلال تنويع المهام والأنشطة ومستويات الأسئلة بما يتناسب مع مستوياتهم المختلفة.
7. زيادة الفرص التي تتيح للطلاب الحوار والمناقشة والتفسير والتعبير عن أفكارهم، مع تقليل الاعتماد على الشرح المباشر قدر الإمكان.
8. المحافظة على الممارسات الجيدة الظاهرة في الحصة والعمل على نقل أثرها إلى تعلم الطالب بصورة قابلة للملاحظة والقياس",
            DomainScores: new Dictionary<int, GoldenDomainScoreFixture>
            {
                [1] = new GoldenDomainScoreFixture(1, @"بيئة التعلم", 13, 65),
                [2] = new GoldenDomainScoreFixture(2, @"التدريس والتعلم", 9, 45),
                [3] = new GoldenDomainScoreFixture(3, @"تنمية المهارات", 17, 71),
                [4] = new GoldenDomainScoreFixture(4, @"التقويم", 7, 58),
                [5] = new GoldenDomainScoreFixture(5, @"سلوك المتعلمين", 20, 83),
            },
            Strengths: new string[]
            {
                @"سلوك المتعلمين (83%)",
            },
            Weaknesses: new GoldenWeaknessFixture[]
            {
                new GoldenWeaknessFixture(2, @"التدريس والتعلم", 45, @"متحقق بدرجة منخفضة"),
                new GoldenWeaknessFixture(4, @"التقويم", 58, @"متحقق بدرجة متوسطة"),
            },
            ScoresState: new Dictionary<int, GoldenStandardScoreStateFixture>
            {
                [1] = new GoldenStandardScoreStateFixture(
                    StandardId: 1,
                    Score: 1,
                    Evidence: "",
                    Indicators: new string[]
                    {
                    }
                ),
                [2] = new GoldenStandardScoreStateFixture(
                    StandardId: 2,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعامل باحترام مع جميع المتعلمين",
                        @"شعور المتعلمين بالأمان داخل الصف والتعبير عن آرائهم دون خوف من الخطأ",
                        @"خلو البيئة من التنمر أو التهديد",
                    }
                ),
                [3] = new GoldenStandardScoreStateFixture(
                    StandardId: 3,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة وفق مستويات المتعلمين",
                        @"مراعاة الفروق الفردية (الإعاقة والموهوبين).",
                    }
                ),
                [4] = new GoldenStandardScoreStateFixture(
                    StandardId: 4,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بتوقيت كل مرحلة من الدرس ( مقدمة - عرض - تطبيق – غلق )",
                        @"منح المتعلمين الذي يحتاجون وقتاً إضافياً فرصة إضافية دون الإخلال بجدول الحصة",
                        @"الانتقال السلس بين الأنشطة",
                    }
                ),
                [5] = new GoldenStandardScoreStateFixture(
                    StandardId: 5,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إشراك جميع المتعلمين",
                    }
                ),
                [6] = new GoldenStandardScoreStateFixture(
                    StandardId: 6,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر تعلم متنوعة داخل الحصة (عرض، فيديو، أوراق عمل، منصة رقمية).",
                    }
                ),
                [7] = new GoldenStandardScoreStateFixture(
                    StandardId: 7,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة والاستراتيجيات المرتبطة بأهداف الدرس.",
                    }
                ),
                [8] = new GoldenStandardScoreStateFixture(
                    StandardId: 8,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الاستراتيجيات وفق مستويات المتعلمين",
                    }
                ),
                [9] = new GoldenStandardScoreStateFixture(
                    StandardId: 9,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر رقمية متنوعة (منصة، فيديو، تطبيق) تخدم أهداف الدرس.",
                    }
                ),
                [10] = new GoldenStandardScoreStateFixture(
                    StandardId: 10,
                    Score: 1,
                    Evidence: "",
                    Indicators: new string[]
                    {
                    }
                ),
                [11] = new GoldenStandardScoreStateFixture(
                    StandardId: 11,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تضمين أنشطة قراءة وكتابة مرتبطة بالدرس",
                        @"تشجيع المتعلمين على التعبير والكتابة والمشاركة",
                        @"تصحيح الأخطاء والسلامة اللغوية",
                    }
                ),
                [12] = new GoldenStandardScoreStateFixture(
                    StandardId: 12,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تشجيع المتعلمين على استخدام مهارات التقدير (مثل: تقدير زمن المهمة، تقدير المسافات)",
                        @"استخدام المتعلمين للمصطلحات العددية (أكثر، أقل، ضعف، نسبة مئوية، الترتيب التسلسلي)",
                    }
                ),
                [13] = new GoldenStandardScoreStateFixture(
                    StandardId: 13,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"طرح أسئلة تفكير عليا (تحليل – تفسير – استنتاج) لماذا؟ كيف؟",
                        @"توجيه المتعلمين لاستخراج المعلومات من (الكتاب، مصادر خارجية، أو تجربة ذهنية)",
                    }
                ),
                [14] = new GoldenStandardScoreStateFixture(
                    StandardId: 14,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تعزيز التعاون والعمل الجماعي بين الطلاب وبمهام محددة",
                        @"تنمية مهارات التواصل واحترام آراء الآخرين",
                        @"دعم الثقة بالنفس والتعبير عن المشاعر بشكل إيجابي",
                    }
                ),
                [15] = new GoldenStandardScoreStateFixture(
                    StandardId: 15,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم المعلم التعزيز الإيجابي (لفظي أو معنوي) لتحفيز جميع الطلاب",
                    }
                ),
                [16] = new GoldenStandardScoreStateFixture(
                    StandardId: 16,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"انخراط المتعلمين في تنفيذ الأنشطة الصفية بتركيز عالٍ، مع الالتزام التام بالعمل الجماعي",
                        @"ظهور علامات البهجة والارتياح أثناء التعلم، مع الرغبة المستمرة في إكمال التحديات",
                    }
                ),
                [17] = new GoldenStandardScoreStateFixture(
                    StandardId: 17,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام التقويم في كافة مراحل الحصة (قبلي، بنائي أثناء الشرح، وختامي)",
                        @"توظيف أدوات متنوعة (مثل: الأسئلة الشفهية، الاختبارات القصيرة أو تطبيقات التقويم التقني).",
                    }
                ),
                [18] = new GoldenStandardScoreStateFixture(
                    StandardId: 18,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم طرقاً مختلفة للقياس (مثل: الاختبارات القصيرة، الأنشطة الشفهية، أو المهام الأدائية).",
                    }
                ),
                [19] = new GoldenStandardScoreStateFixture(
                    StandardId: 19,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تقديم التعليق أو التصحيح للمتعلم أثناء أو فور انتهاء المهمة مباشرة لضمان الاستفادة.",
                    }
                ),
                [20] = new GoldenStandardScoreStateFixture(
                    StandardId: 20,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التزام المتعلمين بالتحدث بلغة عربية سليمة طوال زمن الحصة",
                        @"التمسك بالقيم والأخلاق الإسلامية في التعامل والسمت العام",
                    }
                ),
                [21] = new GoldenStandardScoreStateFixture(
                    StandardId: 21,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إظهار الثقة بالنفس أثناء المشاركة وطرح الآراء.",
                        @"يحترم المتعلمون آراء زملائهم ويتعاملون بإيجابية ويشجعون بعضهم أثناء الأنشطة",
                    }
                ),
                [22] = new GoldenStandardScoreStateFixture(
                    StandardId: 22,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"المحافظة على نظافة المكان والأدوات، والحرص على بيئة صفية صحية (تهوية وإضاءة).",
                        @"الالتزام بوضعية الجلوس الصحيحة، والاهتمام بالنظافة الشخصية والترتيب العام.",
                    }
                ),
                [23] = new GoldenStandardScoreStateFixture(
                    StandardId: 23,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بالتعليمات والنظام داخل الحصة دون تكرار التنبيه، والمحافظة على الهدوء",
                        @"الحرص على آداب الاستئذان قبل المشاركة، والالتزام بمواعيد بدء ونهاية الحصة.",
                    }
                ),
                [24] = new GoldenStandardScoreStateFixture(
                    StandardId: 24,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الاعتماد على النفس في إنجاز المهام، والبحث عن المعلومة قبل طلب المساعدة.",
                        @"القدرة على التقييم الذاتي وتصحيح الأخطاء بناءً على التغذية الراجعة.",
                    }
                ),
                [25] = new GoldenStandardScoreStateFixture(
                    StandardId: 25,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعبير عن الاعتزاز بالثقافة والهوية الوطنية، وإظهار التقدير لثقافات ولهجات الآخرين.",
                        @"تجنب أي تعليقات سلبية تجاه الاختلافات الثقافية، والتعامل بروح الانفتاح والاحترام.",
                    }
                ),
            }
        ),
        new GoldenVisitFixture(
            Id: 1726300010001L,
            Date: @"2026-09-14",
            Period: @"الحصة الثالثة",
            TeacherId: 8,
            TeacherName: @"حسام خياط",
            TeacherEmpId: @"10000008",
            Subject: @"دراسات اسلامية",
            Grade: @"الثاني المتوسط",
            LessonTitle: @"زكاة بهيمة الانعام",
            VisitType: @"أولى",
            Attendance: 23,
            Absence: 5,
            EvaluatorName: @"عبد الإله الشريف",
            EvaluatorRole: @"وكيل شؤون الطلاب",
            TotalScore: 61,
            OverallLevel: @"متحقق بدرجة متوسطة",
            Notes: @"يرجى.تفعيل أدوات، وطرق التعلم النشط.",
            DomainScores: new Dictionary<int, GoldenDomainScoreFixture>
            {
                [1] = new GoldenDomainScoreFixture(1, @"بيئة التعلم", 12, 60),
                [2] = new GoldenDomainScoreFixture(2, @"التدريس والتعلم", 11, 55),
                [3] = new GoldenDomainScoreFixture(3, @"تنمية المهارات", 14, 58),
                [4] = new GoldenDomainScoreFixture(4, @"التقويم", 7, 58),
                [5] = new GoldenDomainScoreFixture(5, @"سلوك المتعلمين", 17, 71),
            },
            Strengths: new string[]
            {
            },
            Weaknesses: new GoldenWeaknessFixture[]
            {
                new GoldenWeaknessFixture(1, @"بيئة التعلم", 60, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(2, @"التدريس والتعلم", 55, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(3, @"تنمية المهارات", 58, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(4, @"التقويم", 58, @"متحقق بدرجة متوسطة"),
            },
            ScoresState: new Dictionary<int, GoldenStandardScoreStateFixture>
            {
                [1] = new GoldenStandardScoreStateFixture(
                    StandardId: 1,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أمثلة أو أنشطة مرتبطة بالقيم الإسلامية",
                        @"ربط المحتوى بالهوية الوطنية وتضمين أنشطة تعزز الانتماء للوطن",
                    }
                ),
                [2] = new GoldenStandardScoreStateFixture(
                    StandardId: 2,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعامل باحترام مع جميع المتعلمين",
                    }
                ),
                [3] = new GoldenStandardScoreStateFixture(
                    StandardId: 3,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة وفق مستويات المتعلمين",
                    }
                ),
                [4] = new GoldenStandardScoreStateFixture(
                    StandardId: 4,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"منح المتعلمين الذي يحتاجون وقتاً إضافياً فرصة إضافية دون الإخلال بجدول الحصة",
                    }
                ),
                [5] = new GoldenStandardScoreStateFixture(
                    StandardId: 5,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إشراك جميع المتعلمين",
                    }
                ),
                [6] = new GoldenStandardScoreStateFixture(
                    StandardId: 6,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر تعلم متنوعة داخل الحصة (عرض، فيديو، أوراق عمل، منصة رقمية).",
                    }
                ),
                [7] = new GoldenStandardScoreStateFixture(
                    StandardId: 7,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة والاستراتيجيات المرتبطة بأهداف الدرس.",
                    }
                ),
                [8] = new GoldenStandardScoreStateFixture(
                    StandardId: 8,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الاستراتيجيات وفق مستويات المتعلمين",
                    }
                ),
                [9] = new GoldenStandardScoreStateFixture(
                    StandardId: 9,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر رقمية متنوعة (منصة، فيديو، تطبيق) تخدم أهداف الدرس.",
                    }
                ),
                [10] = new GoldenStandardScoreStateFixture(
                    StandardId: 10,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنفيذ أنشطة عملية يطبق فيها الطلاب ما تعلموه في مواقف من حياتهم اليومية.",
                    }
                ),
                [11] = new GoldenStandardScoreStateFixture(
                    StandardId: 11,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تصحيح الأخطاء والسلامة اللغوية",
                    }
                ),
                [12] = new GoldenStandardScoreStateFixture(
                    StandardId: 12,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"دمج أرقام، إحصائيات، أو تواريخ ضمن سياق الدرس لتعزيز الفهم",
                        @"تشجيع المتعلمين على استخدام مهارات التقدير (مثل: تقدير زمن المهمة، تقدير المسافات)",
                        @"استخدام المتعلمين للمصطلحات العددية (أكثر، أقل، ضعف، نسبة مئوية، الترتيب التسلسلي)",
                    }
                ),
                [13] = new GoldenStandardScoreStateFixture(
                    StandardId: 13,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"طرح أسئلة تفكير عليا (تحليل – تفسير – استنتاج) لماذا؟ كيف؟",
                    }
                ),
                [14] = new GoldenStandardScoreStateFixture(
                    StandardId: 14,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تعزيز التعاون والعمل الجماعي بين الطلاب وبمهام محددة",
                    }
                ),
                [15] = new GoldenStandardScoreStateFixture(
                    StandardId: 15,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم المعلم التعزيز الإيجابي (لفظي أو معنوي) لتحفيز جميع الطلاب",
                        @"يوظف أساليب تشجيعية متنوعة (نقاط – مسابقات – مكافآت - أوسمة)",
                    }
                ),
                [16] = new GoldenStandardScoreStateFixture(
                    StandardId: 16,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"ظهور علامات البهجة والارتياح أثناء التعلم، مع الرغبة المستمرة في إكمال التحديات",
                    }
                ),
                [17] = new GoldenStandardScoreStateFixture(
                    StandardId: 17,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أدوات متنوعة (مثل: الأسئلة الشفهية، الاختبارات القصيرة أو تطبيقات التقويم التقني).",
                    }
                ),
                [18] = new GoldenStandardScoreStateFixture(
                    StandardId: 18,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم طرقاً مختلفة للقياس (مثل: الاختبارات القصيرة، الأنشطة الشفهية، أو المهام الأدائية).",
                    }
                ),
                [19] = new GoldenStandardScoreStateFixture(
                    StandardId: 19,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تقديم التعليق أو التصحيح للمتعلم أثناء أو فور انتهاء المهمة مباشرة لضمان الاستفادة.",
                        @"عدم الاكتفاء بقول (صح أو خطأ)، بل يوضح للمتعلم ""لماذا"" أخطأ وكيف يصحح مساره للوصول للحل الصحيح.",
                    }
                ),
                [20] = new GoldenStandardScoreStateFixture(
                    StandardId: 20,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"اعتزاز المتعلمين بتاريخ ومنجزات الوطن ورموزه في مشاركاتهم وأثناء الأنشطة",
                        @"التمسك بالقيم والأخلاق الإسلامية في التعامل والسمت العام",
                    }
                ),
                [21] = new GoldenStandardScoreStateFixture(
                    StandardId: 21,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إظهار الثقة بالنفس أثناء المشاركة وطرح الآراء.",
                    }
                ),
                [22] = new GoldenStandardScoreStateFixture(
                    StandardId: 22,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"المحافظة على نظافة المكان والأدوات، والحرص على بيئة صفية صحية (تهوية وإضاءة).",
                    }
                ),
                [23] = new GoldenStandardScoreStateFixture(
                    StandardId: 23,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الحرص على آداب الاستئذان قبل المشاركة، والالتزام بمواعيد بدء ونهاية الحصة.",
                    }
                ),
                [24] = new GoldenStandardScoreStateFixture(
                    StandardId: 24,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الاعتماد على النفس في إنجاز المهام، والبحث عن المعلومة قبل طلب المساعدة.",
                    }
                ),
                [25] = new GoldenStandardScoreStateFixture(
                    StandardId: 25,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعبير عن الاعتزاز بالثقافة والهوية الوطنية، وإظهار التقدير لثقافات ولهجات الآخرين.",
                        @"تجنب أي تعليقات سلبية تجاه الاختلافات الثقافية، والتعامل بروح الانفتاح والاحترام.",
                    }
                ),
            }
        ),
        new GoldenVisitFixture(
            Id: 1726300020002L,
            Date: @"2026-09-14",
            Period: @"الحصة الرابعة",
            TeacherId: 6,
            TeacherName: @"مشاري اللحياني",
            TeacherEmpId: @"10000006",
            Subject: @"دراسات اسلامية",
            Grade: @"الأول المتوسط",
            LessonTitle: @"الطهارة احكام النجاسة",
            VisitType: @"أولى",
            Attendance: 27,
            Absence: 0,
            EvaluatorName: @"عبد الإله الشريف",
            EvaluatorRole: @"وكيل شؤون الطلاب",
            TotalScore: 59,
            OverallLevel: @"متحقق بدرجة متوسطة",
            Notes: @"نأمل تفعيل استراتجيات التعلم النشط",
            DomainScores: new Dictionary<int, GoldenDomainScoreFixture>
            {
                [1] = new GoldenDomainScoreFixture(1, @"بيئة التعلم", 13, 65),
                [2] = new GoldenDomainScoreFixture(2, @"التدريس والتعلم", 10, 50),
                [3] = new GoldenDomainScoreFixture(3, @"تنمية المهارات", 12, 50),
                [4] = new GoldenDomainScoreFixture(4, @"التقويم", 6, 50),
                [5] = new GoldenDomainScoreFixture(5, @"سلوك المتعلمين", 18, 75),
            },
            Strengths: new string[]
            {
                @"سلوك المتعلمين (75%)",
            },
            Weaknesses: new GoldenWeaknessFixture[]
            {
                new GoldenWeaknessFixture(2, @"التدريس والتعلم", 50, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(3, @"تنمية المهارات", 50, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(4, @"التقويم", 50, @"متحقق بدرجة متوسطة"),
            },
            ScoresState: new Dictionary<int, GoldenStandardScoreStateFixture>
            {
                [1] = new GoldenStandardScoreStateFixture(
                    StandardId: 1,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أمثلة أو أنشطة مرتبطة بالقيم الإسلامية",
                        @"ربط المحتوى بالهوية الوطنية وتضمين أنشطة تعزز الانتماء للوطن",
                    }
                ),
                [2] = new GoldenStandardScoreStateFixture(
                    StandardId: 2,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعامل باحترام مع جميع المتعلمين",
                        @"شعور المتعلمين بالأمان داخل الصف والتعبير عن آرائهم دون خوف من الخطأ",
                        @"خلو البيئة من التنمر أو التهديد",
                    }
                ),
                [3] = new GoldenStandardScoreStateFixture(
                    StandardId: 3,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة وفق مستويات المتعلمين",
                    }
                ),
                [4] = new GoldenStandardScoreStateFixture(
                    StandardId: 4,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بتوقيت كل مرحلة من الدرس ( مقدمة - عرض - تطبيق – غلق )",
                    }
                ),
                [5] = new GoldenStandardScoreStateFixture(
                    StandardId: 5,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إشراك جميع المتعلمين",
                    }
                ),
                [6] = new GoldenStandardScoreStateFixture(
                    StandardId: 6,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر تعلم متنوعة داخل الحصة (عرض، فيديو، أوراق عمل، منصة رقمية).",
                    }
                ),
                [7] = new GoldenStandardScoreStateFixture(
                    StandardId: 7,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة والاستراتيجيات المرتبطة بأهداف الدرس.",
                    }
                ),
                [8] = new GoldenStandardScoreStateFixture(
                    StandardId: 8,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الاستراتيجيات وفق مستويات المتعلمين",
                    }
                ),
                [9] = new GoldenStandardScoreStateFixture(
                    StandardId: 9,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر رقمية متنوعة (منصة، فيديو، تطبيق) تخدم أهداف الدرس.",
                    }
                ),
                [10] = new GoldenStandardScoreStateFixture(
                    StandardId: 10,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنفيذ أنشطة عملية يطبق فيها الطلاب ما تعلموه في مواقف من حياتهم اليومية.",
                    }
                ),
                [11] = new GoldenStandardScoreStateFixture(
                    StandardId: 11,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تضمين أنشطة قراءة وكتابة مرتبطة بالدرس",
                    }
                ),
                [12] = new GoldenStandardScoreStateFixture(
                    StandardId: 12,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"دمج أرقام، إحصائيات، أو تواريخ ضمن سياق الدرس لتعزيز الفهم",
                    }
                ),
                [13] = new GoldenStandardScoreStateFixture(
                    StandardId: 13,
                    Score: 1,
                    Evidence: "",
                    Indicators: new string[]
                    {
                    }
                ),
                [14] = new GoldenStandardScoreStateFixture(
                    StandardId: 14,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تعزيز التعاون والعمل الجماعي بين الطلاب وبمهام محددة",
                    }
                ),
                [15] = new GoldenStandardScoreStateFixture(
                    StandardId: 15,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"النجاح في جعل المتعلمين يبادرون بالمشاركة والحماس للأنشطة طوال وقت الحصة",
                    }
                ),
                [16] = new GoldenStandardScoreStateFixture(
                    StandardId: 16,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"مبادرة المتعلمين للمشاركة وطرح الأسئلة بوضوح وحماس طوال الحصة",
                        @"ظهور علامات البهجة والارتياح أثناء التعلم، مع الرغبة المستمرة في إكمال التحديات",
                    }
                ),
                [17] = new GoldenStandardScoreStateFixture(
                    StandardId: 17,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام التقويم في كافة مراحل الحصة (قبلي، بنائي أثناء الشرح، وختامي)",
                    }
                ),
                [18] = new GoldenStandardScoreStateFixture(
                    StandardId: 18,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم طرقاً مختلفة للقياس (مثل: الاختبارات القصيرة، الأنشطة الشفهية، أو المهام الأدائية).",
                    }
                ),
                [19] = new GoldenStandardScoreStateFixture(
                    StandardId: 19,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تقديم التعليق أو التصحيح للمتعلم أثناء أو فور انتهاء المهمة مباشرة لضمان الاستفادة.",
                    }
                ),
                [20] = new GoldenStandardScoreStateFixture(
                    StandardId: 20,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"اعتزاز المتعلمين بتاريخ ومنجزات الوطن ورموزه في مشاركاتهم وأثناء الأنشطة",
                        @"التمسك بالقيم والأخلاق الإسلامية في التعامل والسمت العام",
                    }
                ),
                [21] = new GoldenStandardScoreStateFixture(
                    StandardId: 21,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إظهار الثقة بالنفس أثناء المشاركة وطرح الآراء.",
                    }
                ),
                [22] = new GoldenStandardScoreStateFixture(
                    StandardId: 22,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"المحافظة على نظافة المكان والأدوات، والحرص على بيئة صفية صحية (تهوية وإضاءة).",
                        @"الالتزام بوضعية الجلوس الصحيحة، والاهتمام بالنظافة الشخصية والترتيب العام.",
                    }
                ),
                [23] = new GoldenStandardScoreStateFixture(
                    StandardId: 23,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بالتعليمات والنظام داخل الحصة دون تكرار التنبيه، والمحافظة على الهدوء",
                    }
                ),
                [24] = new GoldenStandardScoreStateFixture(
                    StandardId: 24,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الاعتماد على النفس في إنجاز المهام، والبحث عن المعلومة قبل طلب المساعدة.",
                    }
                ),
                [25] = new GoldenStandardScoreStateFixture(
                    StandardId: 25,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعبير عن الاعتزاز بالثقافة والهوية الوطنية، وإظهار التقدير لثقافات ولهجات الآخرين.",
                        @"تجنب أي تعليقات سلبية تجاه الاختلافات الثقافية، والتعامل بروح الانفتاح والاحترام.",
                    }
                ),
            }
        ),
        new GoldenVisitFixture(
            Id: 1726300030003L,
            Date: @"2026-09-14",
            Period: @"الحصة الخامسة",
            TeacherId: 9,
            TeacherName: @"عبدالرحمن العمودي",
            TeacherEmpId: @"10000009",
            Subject: @"دراسات اسلامية",
            Grade: @"الأول المتوسط",
            LessonTitle: @"تفسير سورتي النصر والكافرون",
            VisitType: @"أولى",
            Attendance: 25,
            Absence: 1,
            EvaluatorName: @"عبد الإله الشريف",
            EvaluatorRole: @"وكيل شؤون الطلاب",
            TotalScore: 59,
            OverallLevel: @"متحقق بدرجة متوسطة",
            Notes: @"نأمل تنويع استراتجيات التعلم النشط اكثر",
            DomainScores: new Dictionary<int, GoldenDomainScoreFixture>
            {
                [1] = new GoldenDomainScoreFixture(1, @"بيئة التعلم", 13, 65),
                [2] = new GoldenDomainScoreFixture(2, @"التدريس والتعلم", 11, 55),
                [3] = new GoldenDomainScoreFixture(3, @"تنمية المهارات", 12, 50),
                [4] = new GoldenDomainScoreFixture(4, @"التقويم", 6, 50),
                [5] = new GoldenDomainScoreFixture(5, @"سلوك المتعلمين", 17, 71),
            },
            Strengths: new string[]
            {
            },
            Weaknesses: new GoldenWeaknessFixture[]
            {
                new GoldenWeaknessFixture(2, @"التدريس والتعلم", 55, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(3, @"تنمية المهارات", 50, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(4, @"التقويم", 50, @"متحقق بدرجة متوسطة"),
            },
            ScoresState: new Dictionary<int, GoldenStandardScoreStateFixture>
            {
                [1] = new GoldenStandardScoreStateFixture(
                    StandardId: 1,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أمثلة أو أنشطة مرتبطة بالقيم الإسلامية",
                        @"ربط المحتوى بالهوية الوطنية وتضمين أنشطة تعزز الانتماء للوطن",
                    }
                ),
                [2] = new GoldenStandardScoreStateFixture(
                    StandardId: 2,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعامل باحترام مع جميع المتعلمين",
                        @"شعور المتعلمين بالأمان داخل الصف والتعبير عن آرائهم دون خوف من الخطأ",
                        @"خلو البيئة من التنمر أو التهديد",
                    }
                ),
                [3] = new GoldenStandardScoreStateFixture(
                    StandardId: 3,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة وفق مستويات المتعلمين",
                    }
                ),
                [4] = new GoldenStandardScoreStateFixture(
                    StandardId: 4,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الانتقال السلس بين الأنشطة",
                    }
                ),
                [5] = new GoldenStandardScoreStateFixture(
                    StandardId: 5,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إشراك جميع المتعلمين",
                    }
                ),
                [6] = new GoldenStandardScoreStateFixture(
                    StandardId: 6,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر تعلم متنوعة داخل الحصة (عرض، فيديو، أوراق عمل، منصة رقمية).",
                    }
                ),
                [7] = new GoldenStandardScoreStateFixture(
                    StandardId: 7,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة والاستراتيجيات المرتبطة بأهداف الدرس.",
                    }
                ),
                [8] = new GoldenStandardScoreStateFixture(
                    StandardId: 8,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الاستراتيجيات وفق مستويات المتعلمين",
                    }
                ),
                [9] = new GoldenStandardScoreStateFixture(
                    StandardId: 9,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر رقمية متنوعة (منصة، فيديو، تطبيق) تخدم أهداف الدرس.",
                    }
                ),
                [10] = new GoldenStandardScoreStateFixture(
                    StandardId: 10,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنفيذ أنشطة عملية يطبق فيها الطلاب ما تعلموه في مواقف من حياتهم اليومية.",
                    }
                ),
                [11] = new GoldenStandardScoreStateFixture(
                    StandardId: 11,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تضمين أنشطة قراءة وكتابة مرتبطة بالدرس",
                    }
                ),
                [12] = new GoldenStandardScoreStateFixture(
                    StandardId: 12,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"دمج أرقام، إحصائيات، أو تواريخ ضمن سياق الدرس لتعزيز الفهم",
                    }
                ),
                [13] = new GoldenStandardScoreStateFixture(
                    StandardId: 13,
                    Score: 1,
                    Evidence: "",
                    Indicators: new string[]
                    {
                    }
                ),
                [14] = new GoldenStandardScoreStateFixture(
                    StandardId: 14,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تعزيز التعاون والعمل الجماعي بين الطلاب وبمهام محددة",
                    }
                ),
                [15] = new GoldenStandardScoreStateFixture(
                    StandardId: 15,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم المعلم التعزيز الإيجابي (لفظي أو معنوي) لتحفيز جميع الطلاب",
                    }
                ),
                [16] = new GoldenStandardScoreStateFixture(
                    StandardId: 16,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"انخراط المتعلمين في تنفيذ الأنشطة الصفية بتركيز عالٍ، مع الالتزام التام بالعمل الجماعي",
                        @"ظهور علامات البهجة والارتياح أثناء التعلم، مع الرغبة المستمرة في إكمال التحديات",
                    }
                ),
                [17] = new GoldenStandardScoreStateFixture(
                    StandardId: 17,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أدوات متنوعة (مثل: الأسئلة الشفهية، الاختبارات القصيرة أو تطبيقات التقويم التقني).",
                    }
                ),
                [18] = new GoldenStandardScoreStateFixture(
                    StandardId: 18,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم طرقاً مختلفة للقياس (مثل: الاختبارات القصيرة، الأنشطة الشفهية، أو المهام الأدائية).",
                    }
                ),
                [19] = new GoldenStandardScoreStateFixture(
                    StandardId: 19,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تقديم التعليق أو التصحيح للمتعلم أثناء أو فور انتهاء المهمة مباشرة لضمان الاستفادة.",
                    }
                ),
                [20] = new GoldenStandardScoreStateFixture(
                    StandardId: 20,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"اعتزاز المتعلمين بتاريخ ومنجزات الوطن ورموزه في مشاركاتهم وأثناء الأنشطة",
                        @"التمسك بالقيم والأخلاق الإسلامية في التعامل والسمت العام",
                    }
                ),
                [21] = new GoldenStandardScoreStateFixture(
                    StandardId: 21,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إظهار الثقة بالنفس أثناء المشاركة وطرح الآراء.",
                    }
                ),
                [22] = new GoldenStandardScoreStateFixture(
                    StandardId: 22,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"المحافظة على نظافة المكان والأدوات، والحرص على بيئة صفية صحية (تهوية وإضاءة).",
                        @"الالتزام بوضعية الجلوس الصحيحة، والاهتمام بالنظافة الشخصية والترتيب العام.",
                    }
                ),
                [23] = new GoldenStandardScoreStateFixture(
                    StandardId: 23,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بالتعليمات والنظام داخل الحصة دون تكرار التنبيه، والمحافظة على الهدوء",
                        @"الحرص على آداب الاستئذان قبل المشاركة، والالتزام بمواعيد بدء ونهاية الحصة.",
                    }
                ),
                [24] = new GoldenStandardScoreStateFixture(
                    StandardId: 24,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الاعتماد على النفس في إنجاز المهام، والبحث عن المعلومة قبل طلب المساعدة.",
                    }
                ),
                [25] = new GoldenStandardScoreStateFixture(
                    StandardId: 25,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعبير عن الاعتزاز بالثقافة والهوية الوطنية، وإظهار التقدير لثقافات ولهجات الآخرين.",
                        @"تجنب أي تعليقات سلبية تجاه الاختلافات الثقافية، والتعامل بروح الانفتاح والاحترام.",
                    }
                ),
            }
        ),
        new GoldenVisitFixture(
            Id: 1726300040004L,
            Date: @"2026-09-14",
            Period: @"الحصة السادسة",
            TeacherId: 7,
            TeacherName: @"علي المباركي",
            TeacherEmpId: @"10000007",
            Subject: @"دراسات اسلامية",
            Grade: @"الثالث المتوسط",
            LessonTitle: @"احكام الاطعمة والاشربة",
            VisitType: @"أولى",
            Attendance: 23,
            Absence: 5,
            EvaluatorName: @"عبد الإله الشريف",
            EvaluatorRole: @"وكيل شؤون الطلاب",
            TotalScore: 67,
            OverallLevel: @"متحقق بدرجة مرتفعة",
            Notes: @"اقترح التوازن بين الطرح العلمي، والأنشطة. وعدم التوسع.",
            DomainScores: new Dictionary<int, GoldenDomainScoreFixture>
            {
                [1] = new GoldenDomainScoreFixture(1, @"بيئة التعلم", 16, 80),
                [2] = new GoldenDomainScoreFixture(2, @"التدريس والتعلم", 12, 60),
                [3] = new GoldenDomainScoreFixture(3, @"تنمية المهارات", 13, 54),
                [4] = new GoldenDomainScoreFixture(4, @"التقويم", 8, 67),
                [5] = new GoldenDomainScoreFixture(5, @"سلوك المتعلمين", 18, 75),
            },
            Strengths: new string[]
            {
                @"بيئة التعلم (80%)",
                @"سلوك المتعلمين (75%)",
            },
            Weaknesses: new GoldenWeaknessFixture[]
            {
                new GoldenWeaknessFixture(2, @"التدريس والتعلم", 60, @"متحقق بدرجة متوسطة"),
                new GoldenWeaknessFixture(3, @"تنمية المهارات", 54, @"متحقق بدرجة متوسطة"),
            },
            ScoresState: new Dictionary<int, GoldenStandardScoreStateFixture>
            {
                [1] = new GoldenStandardScoreStateFixture(
                    StandardId: 1,
                    Score: 4,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أمثلة أو أنشطة مرتبطة بالقيم الإسلامية",
                        @"ربط المحتوى بالهوية الوطنية وتضمين أنشطة تعزز الانتماء للوطن",
                    }
                ),
                [2] = new GoldenStandardScoreStateFixture(
                    StandardId: 2,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعامل باحترام مع جميع المتعلمين",
                        @"شعور المتعلمين بالأمان داخل الصف والتعبير عن آرائهم دون خوف من الخطأ",
                        @"خلو البيئة من التنمر أو التهديد",
                    }
                ),
                [3] = new GoldenStandardScoreStateFixture(
                    StandardId: 3,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنوع الأنشطة وفق مستويات المتعلمين",
                    }
                ),
                [4] = new GoldenStandardScoreStateFixture(
                    StandardId: 4,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بتوقيت كل مرحلة من الدرس ( مقدمة - عرض - تطبيق – غلق )",
                        @"الانتقال السلس بين الأنشطة",
                    }
                ),
                [5] = new GoldenStandardScoreStateFixture(
                    StandardId: 5,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إشراك جميع المتعلمين",
                        @"عدالة توزيع الفرص وتشجيع الطلاب المنعزلين عن المشاركة",
                    }
                ),
                [6] = new GoldenStandardScoreStateFixture(
                    StandardId: 6,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر تعلم متنوعة داخل الحصة (عرض، فيديو، أوراق عمل، منصة رقمية).",
                    }
                ),
                [7] = new GoldenStandardScoreStateFixture(
                    StandardId: 7,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"وضوح ارتباط الأنشطة بنواتج التعلم.",
                        @"تحقق نواتج التعلم من خلال تنفيذ الأنشطة.",
                    }
                ),
                [8] = new GoldenStandardScoreStateFixture(
                    StandardId: 8,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"مشاركة جميع المتعلمين حسب قدراتهم",
                    }
                ),
                [9] = new GoldenStandardScoreStateFixture(
                    StandardId: 9,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"استخدام مصادر رقمية متنوعة (منصة، فيديو، تطبيق) تخدم أهداف الدرس.",
                    }
                ),
                [10] = new GoldenStandardScoreStateFixture(
                    StandardId: 10,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تنفيذ أنشطة عملية يطبق فيها الطلاب ما تعلموه في مواقف من حياتهم اليومية.",
                    }
                ),
                [11] = new GoldenStandardScoreStateFixture(
                    StandardId: 11,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تصحيح الأخطاء والسلامة اللغوية",
                    }
                ),
                [12] = new GoldenStandardScoreStateFixture(
                    StandardId: 12,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"دمج أرقام، إحصائيات، أو تواريخ ضمن سياق الدرس لتعزيز الفهم",
                    }
                ),
                [13] = new GoldenStandardScoreStateFixture(
                    StandardId: 13,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"طرح أسئلة تفكير عليا (تحليل – تفسير – استنتاج) لماذا؟ كيف؟",
                    }
                ),
                [14] = new GoldenStandardScoreStateFixture(
                    StandardId: 14,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"دعم الثقة بالنفس والتعبير عن المشاعر بشكل إيجابي",
                    }
                ),
                [15] = new GoldenStandardScoreStateFixture(
                    StandardId: 15,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم المعلم التعزيز الإيجابي (لفظي أو معنوي) لتحفيز جميع الطلاب",
                        @"النجاح في جعل المتعلمين يبادرون بالمشاركة والحماس للأنشطة طوال وقت الحصة",
                    }
                ),
                [16] = new GoldenStandardScoreStateFixture(
                    StandardId: 16,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"مبادرة المتعلمين للمشاركة وطرح الأسئلة بوضوح وحماس طوال الحصة",
                        @"انخراط المتعلمين في تنفيذ الأنشطة الصفية بتركيز عالٍ، مع الالتزام التام بالعمل الجماعي",
                        @"ظهور علامات البهجة والارتياح أثناء التعلم، مع الرغبة المستمرة في إكمال التحديات",
                    }
                ),
                [17] = new GoldenStandardScoreStateFixture(
                    StandardId: 17,
                    Score: 2,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"توظيف أدوات متنوعة (مثل: الأسئلة الشفهية، الاختبارات القصيرة أو تطبيقات التقويم التقني).",
                    }
                ),
                [18] = new GoldenStandardScoreStateFixture(
                    StandardId: 18,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"يستخدم طرقاً مختلفة للقياس (مثل: الاختبارات القصيرة، الأنشطة الشفهية، أو المهام الأدائية).",
                        @"يتأكد أن كل سؤال أو نشاط يقيس فعلياً هدفاً محدداً من أهداف الدرس (نواتج التعلم)",
                        @"يستطيع من خلال التقويم تحديد مستوى كل طالب (من أتقن المهارة ومن يحتاج إلى دعم إضافي)",
                    }
                ),
                [19] = new GoldenStandardScoreStateFixture(
                    StandardId: 19,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"تقديم التعليق أو التصحيح للمتعلم أثناء أو فور انتهاء المهمة مباشرة لضمان الاستفادة.",
                        @"عدم الاكتفاء بقول (صح أو خطأ)، بل يوضح للمتعلم ""لماذا"" أخطأ وكيف يصحح مساره للوصول للحل الصحيح.",
                    }
                ),
                [20] = new GoldenStandardScoreStateFixture(
                    StandardId: 20,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"اعتزاز المتعلمين بتاريخ ومنجزات الوطن ورموزه في مشاركاتهم وأثناء الأنشطة",
                        @"التمسك بالقيم والأخلاق الإسلامية في التعامل والسمت العام",
                    }
                ),
                [21] = new GoldenStandardScoreStateFixture(
                    StandardId: 21,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"إظهار الثقة بالنفس أثناء المشاركة وطرح الآراء.",
                        @"يحترم المتعلمون آراء زملائهم ويتعاملون بإيجابية ويشجعون بعضهم أثناء الأنشطة",
                    }
                ),
                [22] = new GoldenStandardScoreStateFixture(
                    StandardId: 22,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"المحافظة على نظافة المكان والأدوات، والحرص على بيئة صفية صحية (تهوية وإضاءة).",
                        @"الالتزام بوضعية الجلوس الصحيحة، والاهتمام بالنظافة الشخصية والترتيب العام.",
                    }
                ),
                [23] = new GoldenStandardScoreStateFixture(
                    StandardId: 23,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الالتزام بالتعليمات والنظام داخل الحصة دون تكرار التنبيه، والمحافظة على الهدوء",
                        @"الحرص على آداب الاستئذان قبل المشاركة، والالتزام بمواعيد بدء ونهاية الحصة.",
                    }
                ),
                [24] = new GoldenStandardScoreStateFixture(
                    StandardId: 24,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"الاعتماد على النفس في إنجاز المهام، والبحث عن المعلومة قبل طلب المساعدة.",
                    }
                ),
                [25] = new GoldenStandardScoreStateFixture(
                    StandardId: 25,
                    Score: 3,
                    Evidence: "",
                    Indicators: new string[]
                    {
                        @"التعبير عن الاعتزاز بالثقافة والهوية الوطنية، وإظهار التقدير لثقافات ولهجات الآخرين.",
                        @"تجنب أي تعليقات سلبية تجاه الاختلافات الثقافية، والتعامل بروح الانفتاح والاحترام.",
                    }
                ),
            }
        ),
    });

    // ─── 24 Default Teachers Fixture ───
    public static readonly ReadOnlyCollection<GoldenTeacherFixture> DefaultTeachers = new(new GoldenTeacherFixture[]
    {
        new GoldenTeacherFixture(
            Id: 1,
            Name: @"جمال حوشبي",
            EmpId: @"10000001",
            Subject: @"اللغة الإنجليزية",
            Grade: @"أول متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"أول متوسط / 2",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 2,
            Name: @"محمود السعيد",
            EmpId: @"10000002",
            Subject: @"اللغة الإنجليزية",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 3,
            Name: @"عبدالله الحساني",
            EmpId: @"10000003",
            Subject: @"اللغة الإنجليزية، مهارات حياتية",
            Grade: @"أول متوسط، ثاني متوسط",
            Classes: new string[]
            {
                @"أول متوسط / 1",
                @"أول متوسط / 3",
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
            }
        ),
        new GoldenTeacherFixture(
            Id: 4,
            Name: @"أحمد اللقماني",
            EmpId: @"10000004",
            Subject: @"الدراسات الاجتماعية، مهارات حياتية",
            Grade: @"أول متوسط، ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 4",
                @"أول متوسط / 1",
                @"أول متوسط / 2",
            }
        ),
        new GoldenTeacherFixture(
            Id: 5,
            Name: @"منصور الكحيلي",
            EmpId: @"10000005",
            Subject: @"الدراسات الاجتماعية، مهارات حياتية",
            Grade: @"أول متوسط، ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"ثاني متوسط / 2",
                @"ثاني متوسط / 3",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 6,
            Name: @"مشاري اللحياني",
            EmpId: @"10000006",
            Subject: @"الدراسات الإسلامية، مهارات حياتية",
            Grade: @"أول متوسط، ثاني متوسط",
            Classes: new string[]
            {
                @"ثاني متوسط / 4",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 7,
            Name: @"علي المباركي",
            EmpId: @"10000007",
            Subject: @"الدراسات الإسلامية، التفكير الناقد",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"ثاني متوسط / 1",
            }
        ),
        new GoldenTeacherFixture(
            Id: 8,
            Name: @"حسام خياط",
            EmpId: @"10000008",
            Subject: @"الدراسات الإسلامية، التفكير الناقد",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثاني متوسط / 2",
                @"ثاني متوسط / 3",
            }
        ),
        new GoldenTeacherFixture(
            Id: 9,
            Name: @"عبدالرحمن العمودي",
            EmpId: @"10000009",
            Subject: @"الدراسات الإسلامية، مهارات حياتية",
            Grade: @"أول متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 2",
                @"أول متوسط / 1",
                @"أول متوسط / 2",
            }
        ),
        new GoldenTeacherFixture(
            Id: 10,
            Name: @"محمد زيني",
            EmpId: @"10000010",
            Subject: @"اللغة العربية",
            Grade: @"أول متوسط، ثاني متوسط",
            Classes: new string[]
            {
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 11,
            Name: @"مؤيد اللقماني",
            EmpId: @"10000011",
            Subject: @"اللغة العربية، التفكير الناقد",
            Grade: @"أول متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"أول متوسط / 1",
                @"أول متوسط / 2",
            }
        ),
        new GoldenTeacherFixture(
            Id: 12,
            Name: @"حسام الزهراني",
            EmpId: @"10000012",
            Subject: @"اللغة العربية، التفكير الناقد",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
            }
        ),
        new GoldenTeacherFixture(
            Id: 13,
            Name: @"فؤاد فلمبان",
            EmpId: @"10000013",
            Subject: @"التربية البدنية",
            Grade: @"ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 14,
            Name: @"مشعل المالكي",
            EmpId: @"10000014",
            Subject: @"التربية البدنية",
            Grade: @"أول متوسط، ثاني متوسط",
            Classes: new string[]
            {
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
                @"أول متوسط / 1",
                @"أول متوسط / 2",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 15,
            Name: @"حسين خرد",
            EmpId: @"10000015",
            Subject: @"المهارات الرقمية",
            Grade: @"أول متوسط",
            Classes: new string[]
            {
                @"أول متوسط / 1",
                @"أول متوسط / 2",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 16,
            Name: @"أحمد الدسوقي",
            EmpId: @"10000016",
            Subject: @"المهارات الرقمية",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 17,
            Name: @"أكرم المطرفي",
            EmpId: @"10000017",
            Subject: @"الرياضيات",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 18,
            Name: @"عبدالله سليم",
            EmpId: @"10000018",
            Subject: @"الرياضيات",
            Grade: @"أول متوسط",
            Classes: new string[]
            {
                @"أول متوسط / 2",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 19,
            Name: @"خيري مصطفى",
            EmpId: @"10000019",
            Subject: @"الرياضيات",
            Grade: @"أول متوسط، ثاني متوسط",
            Classes: new string[]
            {
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
                @"أول متوسط / 1",
            }
        ),
        new GoldenTeacherFixture(
            Id: 20,
            Name: @"محمد العسيري",
            EmpId: @"10000020",
            Subject: @"الرياضيات",
            Grade: @"ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 2",
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 21,
            Name: @"يزن الظاهري",
            EmpId: @"10000021",
            Subject: @"العلوم",
            Grade: @"ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 22,
            Name: @"ماجد باعارمة",
            EmpId: @"10000022",
            Subject: @"العلوم",
            Grade: @"أول متوسط، ثاني متوسط",
            Classes: new string[]
            {
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
        new GoldenTeacherFixture(
            Id: 23,
            Name: @"عبدالله المالكي",
            EmpId: @"10000023",
            Subject: @"العلوم",
            Grade: @"أول متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"أول متوسط / 1",
                @"أول متوسط / 2",
            }
        ),
        new GoldenTeacherFixture(
            Id: 24,
            Name: @"مؤيد خياط",
            EmpId: @"10000024",
            Subject: @"التربية الفنية",
            Grade: @"أول متوسط، ثاني متوسط، ثالث متوسط",
            Classes: new string[]
            {
                @"ثالث متوسط / 1",
                @"ثالث متوسط / 2",
                @"ثالث متوسط / 3",
                @"ثالث متوسط / 4",
                @"ثاني متوسط / 1",
                @"ثاني متوسط / 2",
                @"ثاني متوسط / 3",
                @"ثاني متوسط / 4",
                @"أول متوسط / 1",
                @"أول متوسط / 2",
                @"أول متوسط / 3",
                @"أول متوسط / 4",
            }
        ),
    });
}

// ─── Model Records ───
public record GoldenEvaluatorFixture(int Id, string Name, string Role);
public record GoldenTreatmentTemplateFixture(string DomainName, string Goal, string Actions, string SuccessIndicators);
public record GoldenDomainFixture(int Id, string Name, IReadOnlyList<GoldenStandardFixture> Standards);
public record GoldenStandardFixture(int Id, int Num, string Text, IReadOnlyList<string> Indicators);
public record GoldenDomainScoreFixture(int DomainId, string DomainName, int Sum, int Percent);
public record GoldenWeaknessFixture(int DomainId, string DomainName, int Percent, string Level);
public record GoldenStandardScoreStateFixture(int StandardId, int Score, string Evidence, IReadOnlyList<string> Indicators);
public record GoldenTeacherFixture(int Id, string Name, string EmpId, string Subject, string Grade, IReadOnlyList<string> Classes);
public record GoldenVisitFixture(
    long Id,
    string Date,
    string Period,
    int TeacherId,
    string TeacherName,
    string TeacherEmpId,
    string Subject,
    string Grade,
    string LessonTitle,
    string VisitType,
    int Attendance,
    int Absence,
    string EvaluatorName,
    string EvaluatorRole,
    int TotalScore,
    string OverallLevel,
    string Notes,
    IReadOnlyDictionary<int, GoldenDomainScoreFixture> DomainScores,
    IReadOnlyList<string> Strengths,
    IReadOnlyList<GoldenWeaknessFixture> Weaknesses,
    IReadOnlyDictionary<int, GoldenStandardScoreStateFixture> ScoresState
);
