import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { finalize } from 'rxjs';
import { GatePassStatus, ManagerGatePassAuditItemDto, gatePassStatusLabel } from '../../../core/models/gate-pass.models';
import { GatePassService } from '../../../core/services/gate-pass.service';
import { ToastService } from '../../../core/services/toast.service';

@Component({selector:'app-manager-gate-pass-audit',standalone:true,imports:[CommonModule,ReactiveFormsModule,ButtonModule],template:`
<main dir="rtl" class="audit-page"><header><div><span>مسار استثنائي مدقق</span><h1>تدقيق استئذانات الخروج</h1><p>الإلغاء متاح للحالات النشطة فقط، وتصحيح الخروج الخاطئ يضيف واقعة دون محو الخروج الأصلي.</p></div><button pButton type="button" class="p-button-outlined" icon="pi pi-refresh" label="تحديث" [loading]="loading()" (click)="load()"></button></header>
<div class="filters"><label>الحالة<select [formControl]="status" (change)="resetAndLoad()"><option value="">كل الحالات</option><option *ngFor="let value of statuses" [value]="value">{{ label(value) }}</option></select></label></div>
<p class="state" role="status" aria-live="polite" *ngIf="loading()">جارٍ تحميل السجل…</p><p class="state error" role="alert" *ngIf="errorMessage()">{{errorMessage()}}</p>
<section class="cards" *ngIf="!loading()&&!errorMessage()"><article *ngFor="let item of items()"><div class="title"><strong>{{item.studentDisplayName}}</strong><span>#{{item.studentNumber}}</span></div><dl><div><dt>الفصل</dt><dd>{{item.classLabel}}</dd></div><div><dt>الحالة</dt><dd>{{label(item.status)}} <b *ngIf="item.isOverdue">· متأخر/استثنائي</b></dd></div><div><dt>موعد الخروج المطلوب</dt><dd>{{item.requestedExitAt|date:'short':'':'ar-EG'}}</dd></div><div><dt>آخر انتقال</dt><dd>{{item.lastTransitionAt|date:'short':'':'ar-EG'}}</dd></div></dl><div class="actions"><button type="button" (click)="showHistory(item)">عرض السجل</button><button type="button" *ngIf="canCancel(item.status)" (click)="begin(item,'cancel')">إلغاء استثنائي</button><button type="button" *ngIf="item.status==='Exited'" (click)="begin(item,'false-exit')">تسجيل خروج خاطئ</button></div></article><p class="state" *ngIf="items().length===0">لا توجد استئذانات مطابقة.</p></section>
<section class="panel" *ngIf="selected() as item"><h2>{{action()==='cancel'?'تأكيد الإلغاء الاستثنائي':'تسجيل واقعة خروج خاطئ'}} — {{item.studentDisplayName}}</h2><p *ngIf="action()==='false-exit'">لن تتغير حالة Exited ولن يُحذف وقت الخروج الأصلي.</p><label>السبب<textarea [formControl]="reason" rows="3" maxlength="1000"></textarea></label><div><button type="button" [disabled]="reason.invalid||saving()" (click)="submit()">تأكيد وحفظ</button><button type="button" [disabled]="saving()" (click)="selected.set(null)">إلغاء</button></div></section>
<section class="panel" *ngIf="history().length"><h2>سجل الانتقالات</h2><ol><li *ngFor="let event of history()"><strong>{{event.toState}}</strong> — {{event.occurredAt|date:'medium':'':'ar-EG'}}<span *ngIf="event.reason"> — {{event.reason}}</span></li></ol></section>
<nav><button type="button" [disabled]="page()===1" (click)="move(-1)">السابق</button><span>صفحة {{page()}} من {{pages()}}</span><button type="button" [disabled]="page()>=pages()" (click)="move(1)">التالي</button></nav></main>`,styles:[`.audit-page{display:grid;gap:1rem;padding:1.25rem}header,.title,.actions,nav{display:flex;justify-content:space-between;gap:.75rem;align-items:center}h1{margin:.25rem 0}.filters,.panel,.state,article{background:var(--surface-card,#fff);border:1px solid var(--surface-border,#ddd);border-radius:14px;padding:1rem}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1rem}dl{display:grid;gap:.5rem}dl div{display:flex;justify-content:space-between;gap:1rem}dt{color:var(--text-color-secondary,#555)}dd{margin:0}.actions{justify-content:flex-start;flex-wrap:wrap}.actions button,.panel button,nav button{padding:.6rem .8rem}select,textarea{font:inherit;padding:.6rem;border:1px solid var(--surface-border,#bbb);border-radius:8px;width:100%;box-sizing:border-box}.panel label{display:grid;gap:.4rem;margin-bottom:.75rem}.error{border-color:#b91c1c}nav{justify-content:center}@media(max-width:600px){header{align-items:stretch;flex-direction:column}}`]
})
export class ManagerGatePassAuditComponent {
 private readonly api=inject(GatePassService); private readonly toast=inject(ToastService); readonly items=signal<readonly ManagerGatePassAuditItemDto[]>([]);readonly loading=signal(true);readonly saving=signal(false);readonly errorMessage=signal('');readonly page=signal(1);readonly total=signal(0);readonly selected=signal<ManagerGatePassAuditItemDto|null>(null);readonly action=signal<'cancel'|'false-exit'>('cancel');readonly history=signal<readonly import('../../../core/models/gate-pass.models').TransitionDto[]>([]);readonly status=new FormControl<GatePassStatus|''>('',{nonNullable:true});readonly reason=new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(1000)]});readonly statuses:readonly GatePassStatus[]=['Requested','Approved','SecurityAcknowledged','Exited','Cancelled','Rejected','Expired'];readonly pageSize=12;
 constructor(){this.load();} pages():number{return Math.max(1,Math.ceil(this.total()/this.pageSize));} label=gatePassStatusLabel; canCancel(s:GatePassStatus):boolean{return ['Requested','Approved','SecurityAcknowledged'].includes(s);} resetAndLoad():void{this.page.set(1);this.load();} move(delta:number):void{this.page.update(x=>x+delta);this.load();}
 load():void{this.loading.set(true);this.errorMessage.set('');this.api.managerAudit({status:this.status.value||undefined,pageNumber:this.page(),pageSize:this.pageSize,sortBy:'requestedExitAt',sortDirection:'desc'}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{if(r.isSuccess&&r.data){this.items.set(r.data.items);this.total.set(r.data.totalCount);}else this.errorMessage.set(r.errors[0]??r.message);},error:(e:HttpErrorResponse)=>this.errorMessage.set(e.status===403?'لا تملك صلاحية تدقيق الاستئذانات.':'تعذر تحميل سجل الاستئذانات.')});}
 begin(item:ManagerGatePassAuditItemDto,action:'cancel'|'false-exit'):void{this.selected.set(item);this.action.set(action);this.reason.setValue('');this.history.set([]);}
 showHistory(item:ManagerGatePassAuditItemDto):void{this.api.history(item.id).subscribe({next:r=>this.history.set(r.data?.transitions??[]),error:()=>this.toast.error('تعذر تحميل السجل','أعد المحاولة لاحقاً.')});}
 submit():void{const item=this.selected();this.reason.markAsTouched();if(!item||this.reason.invalid||this.saving()||!confirm('هل تريد حفظ هذا الإجراء الاستثنائي في سجل التدقيق؟'))return;this.saving.set(true);const request={reason:this.reason.value.trim(),rowVersion:item.rowVersion};const call=this.action()==='cancel'?this.api.cancel(item.id,request):this.api.recordFalseExitIncident(item.id,request);call.pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{if(r.isSuccess){this.toast.success('تم حفظ الإجراء','أضيف إلى السجل المدقق.');this.selected.set(null);this.load();}else this.toast.warn('لم يُحفظ الإجراء',r.errors[0]??r.message);},error:(e:HttpErrorResponse)=>{if(e.status===409){this.toast.warn('تغير السجل','تم تحديث القائمة؛ راجع الحالة الجديدة.');this.selected.set(null);this.load();}else this.toast.error('تعذر الحفظ','لم تتم إعادة الإرسال تلقائياً.');}});}
}
