export interface EvaluationFilter { academicYearId: number; templateVersion: number; domainCode?: string; standardCode?: string; responsibleUserId?: string; importance?: number; status?: string; search?: string; criticalOnly: boolean; hideCompleted: boolean; trackerOnly: boolean; gapsOnly?: boolean; page: number; pageSize: number; }
export interface EvaluationSection { code: string; name: string; sortOrder: number; }
export interface EvaluationTemplate { version: number; name: string; rounding: string; sourceName: string; sourceSha256: string; domains: EvaluationSection[]; standards: EvaluationSection[]; items: unknown[]; matrixReferences: {ordinal:number; state:string}[]; }
export interface ReadinessMetric { code:string; name:string; requirements:number; numerator:number; denominator:number; percentage:number|null; calculationState:string; uniqueFiles:number; links:number; approvedLinks:number; gaps:number; criticalGaps:number; }
export interface ReadinessSummary { schoolId:number; schoolName:string; academicYearId:number; academicYearName:string; templateVersion:number; templateName:string; templateSHA256:string; rounding:string; calculatedAtUtc:string; filters:EvaluationFilter; overall:ReadinessMetric; domains:ReadinessMetric[]; standards:ReadinessMetric[]; }
export interface EvaluationRequirement { id:number; code:string; name:string; domainCode?:string; standardCode?:string; originalTaskId?:number; responsibleUserId?:string; responsibleName:string; responsibleRole?:string; importance:string; isMandatory:boolean; policy:string; requiredLinks:number; links:number; availableLinks:number; approvedLinks:number; fulfilled:boolean; status:string; gapReasons:string[]; completionAction:string; actionUrl:string; availableFileId?:number; referencePath?:string; sourceKey?:string; sourceSHA256?:string; candidateTaskCodes:string[]; mappingStatus:string; dueDate?:string; followUpStatus:string; followUpNote?:string; rowVersion:string; }
export interface EvaluationMember {userId:string; name:string;}
export interface EvaluationVersion {version:number; name:string; sha256:string;}
export interface ManualEvaluation {id:number; scopeCode:string; judgment:string; value?:number; reason:string; evaluatorName:string; evaluatedAtUtc:string; revision:number; rowVersion:string;}
export interface DigitalIndexFile {fileId:number; name:string; mimeType?:string; size:number; links:number; approvedLinks:number;}
