"""Compare actual archived/official V2 PDFs from isolated SQL; never starts API/Drive."""
import hashlib
import json
import re
import sys
from pathlib import Path

import fitz

root = Path(__file__).resolve().parents[4]
folder = Path(sys.argv[1]) if len(sys.argv) > 1 else root / '.audit/sfs-s5/exports'
results = []
for approval in ('manual', 'automatic'):
    archived_path = folder / f'{approval}-archive.pdf'
    official_path = folder / f'{approval}-official.pdf'
    archived = fitz.open(archived_path)
    official = fitz.open(official_path)
    zipped = fitz.open(folder / f'{approval}-zip.pdf')
    assert len(zipped) == len(archived)
    assert len(archived) == len(official) and len(archived) >= 2
    image_rectangles = 0
    fonts = set()
    characters = 0
    zero_mappings = 0
    for index, (page, reference) in enumerate(zip(archived, official)):
        pixels = page.get_pixmap(matrix=fitz.Matrix(1.5, 1.5))
        expected_pixels = reference.get_pixmap(matrix=fitz.Matrix(1.5, 1.5))
        assert pixels.width == expected_pixels.width and pixels.height == expected_pixels.height
        assert pixels.samples == expected_pixels.samples, f'{approval} page {index+1}: rendered snapshot differs'
        assert pixels.samples == zipped[index].get_pixmap(matrix=fitz.Matrix(1.5, 1.5)).samples
        for block in page.get_text('rawdict')['blocks']:
            for line in block.get('lines', []):
                for span in line['spans']:
                    for char in span['chars']:
                        x0, y0, x1, y1 = char['bbox']
                        assert -0.5 <= x0 <= x1 <= page.rect.width+0.5
                        assert -0.5 <= y0 <= y1 <= page.rect.height+0.5
                        characters += 1
        for image in page.get_images(full=True):
            image_rectangles += len(page.get_image_rects(image[0]))
        for font in page.get_fonts(full=True):
            fonts.add(font[3])
        if index in (0, len(archived)-1):
            pixels.save(folder / f'{approval}-page-{index+1}.png')
    assert any('Amiri-Regular' in font for font in fonts)
    assert any('Amiri-Bold' in font for font in fonts)
    assert image_rectangles >= 4, 'frozen logo and three authorized signature fixtures must render'
    for xref in range(1, archived.xref_length()):
        key_type, unicode_ref = archived.xref_get_key(xref, 'ToUnicode')
        if key_type == 'xref':
            stream = archived.xref_stream(int(unicode_ref.split()[0])) or b''
            zero_mappings += len(re.findall(rb'<[0-9A-Fa-f]+>\s*<0000>', stream))
    snapshot = json.loads((folder / f'{approval}-snapshot.json').read_text(encoding='utf-8'))
    assert snapshot['Report']['Analysis']['MaximumScore'] == 100
    assert snapshot['Report']['Analysis']['TotalScore'] == 25
    assert snapshot['Assets']['Frozen'] is True
    assert all(snapshot['Assets'][field].startswith('data:image/') for field in
               ('LogoSource', 'InstructorSignatureSource', 'EvaluatorSignatureSource', 'ManagerSignatureSource'))
    results.append({
        'approval': approval, 'pages': len(archived), 'renderedPagesEqualToOfficialSameSnapshot': True,
        'renderedPagesEqualToZipSameSnapshot': True,
        'charactersWithinPages': characters, 'fonts': sorted(fonts), 'logoAndSignatureRectangles': image_rectangles,
        'pdfBytes': archived_path.stat().st_size,
        'archiveSha256': hashlib.sha256(archived_path.read_bytes()).hexdigest(),
        'officialSha256': hashlib.sha256(official_path.read_bytes()).hexdigest(),
        'zeroShapedGlyphUnicodeMappings': zero_mappings, 'arabicSearchCopyReliable': False,
        'metrics': json.loads((folder / f'{approval}-metrics.json').read_text(encoding='utf-8'))
    })
report = {'stage': 'S5', 'source': 'actual generated bytes, isolated SQL and simulated Drive',
          'reports': results, 'liveGoogleVerified': False,
          'visualReview': 'First and final pages rendered for Arabic/RTL, school branding, signature blocks and pagination review; see S5 verification.'}
destination = Path(sys.argv[2]) if len(sys.argv) > 2 else root / 'docs/specs/school-file-storage/verification/s5-pdf-comparison.json'
destination.write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
print(json.dumps(report, ensure_ascii=False, indent=2))
